name: Build and Release

on:
  push:
    branches:
      - main # 每次推送到 main 分支时触发
    tags:
      - 'v*' # 每次推送带 v 的 tag 时触发

jobs:
  build:
    name: Build macOS App
    runs-on: macos-latest
    permissions:
      contents: write # 给流水线赋予写入 Releases 的权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment and variables
        id: setup_env
        run: |
          set -e
          VERSION="1.1.2"
          BUILD_NUMBER=${GITHUB_RUN_NUMBER}
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi
          echo "APP_VERSION=${VERSION}" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $GITHUB_ENV

      - name: Build App
        run: |
          set -e
          chmod +x build.sh
          ./build.sh

      - name: Package App
        run: |
          set -e
          zip -r AwakeDisplay.zip AwakeDisplay.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AwakeDisplay-macOS
          path: AwakeDisplay.zip

      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # 固定使用 v2.2.1 的 commit sha 降低供应链风险
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: AwakeDisplay.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
